# Generated by Django 4.0.1 on 2022-01-10 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileType', models.CharField(max_length=20, verbose_name='Type')),
                ('fileDate', models.DateField(verbose_name='Date')),
                ('admin', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=20, verbose_name='Name')),
                ('playerClass', models.CharField(max_length=20, verbose_name='Class')),
                ('playerType', models.CharField(max_length=20, verbose_name='Type')),
                ('currentDKP', models.IntegerField(default=0, verbose_name='DKP')),
                ('monthPercent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='30Day')),
                ('lifePercent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Lifetime')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.IntegerField(default=0)),
                ('itemDate', models.DateField(verbose_name='Date')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
    ]
