# Generated by Django 4.0.1 on 2022-01-20 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='fileDate',
            field=models.DateField(default=datetime.date(2022, 1, 20), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemDate',
            field=models.DateField(default=datetime.date(2022, 1, 20), verbose_name='Date'),
        ),
    ]
