# Generated by Django 4.0.1 on 2022-01-20 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_file_filedate_alter_item_itemdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='fileDate',
            field=models.DateField(default=datetime.datetime(2022, 1, 20, 17, 14, 22, 72920), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemDate',
            field=models.DateField(default=datetime.datetime(2022, 1, 20, 17, 14, 22, 72920), verbose_name='Date'),
        ),
    ]
