# Generated by Django 4.0.1 on 2022-01-25 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_file_filedate_alter_item_itemdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='checksAvail',
            field=models.IntegerField(default=0, verbose_name='Possible'),
        ),
        migrations.AddField(
            model_name='player',
            name='checksEarned',
            field=models.IntegerField(default=0, verbose_name='Earned'),
        ),
        migrations.AlterField(
            model_name='file',
            name='fileDate',
            field=models.DateField(default=datetime.datetime(2022, 1, 25, 14, 45, 38, 784641), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemDate',
            field=models.DateField(default=datetime.datetime(2022, 1, 25, 14, 45, 38, 784641), verbose_name='Date'),
        ),
    ]
